### ISSUE TITLE
Error when building examples-gen

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/pythonlib#2]
First of all, thanks for developing this fantastic library.

After successfully managing to build `examples`, I tried to build `examples-gen` but ran into the following error:

```
> dune build examples-gen/generated/ocaml.bc.so
File "examples-gen/generated/gen_types.ml", line 99, characters 12-30:
99 |   (fun (x : Bin_prot__.Shape.t) -> (Lazy.force capsule |> fst) x),
                 ^^^^^^^^^^^^^^^^^^
Error: Unbound module Bin_prot__
Done: 134/138 (jobs: 1)⏎                                                                                                                                                               
```

Here is the neighborhood of the problematic code in the generated file `gen_types.ml`:
```ocaml
let python_of_bin_prot____shape__t, bin_prot____shape__t_of_python =
  let capsule = lazy (Py.Capsule.make "Bin_prot__.Shape.t") in
  (fun (x : Bin_prot__.Shape.t) -> (Lazy.force capsule |> fst) x),
  (fun x -> (Lazy.force capsule |> snd) x)
;;
let param_bin_prot____shape__t =
  Defunc.Of_python.create ~type_name:"Bin_prot__.Shape.t" ~conv:bin_prot____shape__t_of_python
;;
```

Any insight on what is happening here? I am using OCaml v4.11.1 and base/core_kernel v0.14.0.

**Comment by LaurentMazare** [comment]
Not sure what is really going on here but I got this to compile by adding the following line to both `examples-gen/generated/gen_import.mli` and `examples-gen/generated/gen_import.ml`.

```ocaml
module Bin_prot__ = Bin_prot
```

I would have think that this kind of alias always exist but obviously this is not the case here.

**Comment by jonathan-laurent** [comment]
Thanks for your quick reply!

> I would have think that this kind of alias always exist but obviously this is not the case here.
Could you tell me more about this? Is this a convention in Jane Street libraries to always define such aliases? If so, why?
Or does this have to do with compiler internals?

**Comment by LaurentMazare** [comment]
I'm not an expert at all on this but I think it's a compiler thing, you can see some mention of how double underscores are used on the [manual](https://caml.inria.fr/pub/docs/manual-ocaml/modulealias.html).
Though maybe the code generator here should automatically "unescape" these and remove trailing `__`.

**Comment by jonathan-laurent** [comment]
Never mind: I had not updated the path to `core_kernel__Date.cmi` in the dune file and so some files did not get regenerated for the newest versions of OCaml and Core_kernel. Everything works now.
