### ISSUE TITLE
Using pythonlib with custom types

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/pythonlib#4]
I was wondering what was the best way to use pythonlib's with custom types.

For example, let's suppose that one defines the following user type:

```ocaml
type custom =
  { foo : string
  ; bar : (int * float) list
  }
[@@deriving python]
```

How can we then write an OCaml function that takes inputs of type `custom`?

A natural way would be to define: 

```ocaml
let param_custom =
  Defunc.Of_python.create
    ~type_name:"custom"
    ~conv:custom_of_python (* automatically generated by ppx_python *)
```

and then write:

```ocaml
let my_fun =
  let%map_open arg = positional "arg" param_custom ~docstring:"" in
  ...

```

But then, how do I define a python function that takes a function argument of type `custom -> custom`?
My guess would be something like this:

```ocaml

let () =
  Py_typerep.Named_types.register_exn
    ~name:"custom"
    ~ocaml_type:"custom"
    ~python_to_ocaml:custom_of_python
    ~ocaml_to_python:python_of_custom

let typerep_custom: custom Typerep.t = ???

let my_fun =
  let%map_open f = positional "f" (typerep (Function (typerep_custom, typerep_custom))) ~docstring:"" in
  ...
```

But then, the question is: how am I supposed to fill in the `???` blank above? Indeed, the `Named_types.register_exn` function appears to be creating a suitable typerep on the fly but then it just returns unit instead of giving me access to it:

```ocaml
  let register_exn (type a) ~name ~ocaml_type ~python_to_ocaml ~ocaml_to_python =
    let typename = Typerep_lib.Typename.create ~name () in
    let typerep =
      let module T0 = struct
        type named = a
        type t = a

        let typename_of_named = typename
        let typename_of_t = typename
        let witness = Type_equal.T
      end
      in
      Typerep.Named (Typerep.Named.T0 (module T0), None)
    in
    let t = { typename; typerep; ocaml_type; python_to_ocaml; ocaml_to_python } in
    Hashtbl.add_exn store ~key:name ~data:(T t)
  ;;
```

Am I over-complicating things here?

What would be an idiomatic way to define a python function that receives an argument of type `custom -> custom`?

**Comment by LaurentMazare** [comment]
Actually `Py_typerep` is mostly used when interacting when an embedded top-level. For the usual bindings, there is no real need to use it.
E.g. for your use case, what about the following code? (I haven't tried compiling it but you get the idea).

```ocaml
type custom =
  { foo : string
  ; bar : (int * float) list
  }
[@@deriving python]

let param_custom =
  Defunc.Of_python.create
    ~type_name:"custom"
    ~conv:custom_of_python (* automatically generated by ppx_python *)

let wrapped_fn =
  let%map_open arg = positional "arg" param_custom ~docstring:"" in
  python_of_t { arg with foo = arg.foo ^ "-returned" }

let () =
  if not (Py.is_initialized ())
  then Py.initialize ();
  let mod_ = Py_module.create "sample_ocaml_module" in
  Py_module.set mod_ "wrapped_fn" wrapped_fn
```
Then once you've loaded the shared library from python, you should be able to run the following.
```python
import sample_ocaml_module
print(sample_ocaml_module.wrapped_fn({'foo': 'myfoo', 'bar': [(1, 3.14159), (3, 2.7182818)]})
```

**Comment by jonathan-laurent** [comment]
This makes sense, thank you!
