### ISSUE TITLE
The signature of Pymodule.set is changed on master, breaking the examples

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/pythonlib#8]
I tried to build the examples on master and it failed with the following error:
```
File "examples/ocaml.ml", line 51, characters 27-30:
51 |   Py_module.set mod_ "add" add;
                                ^^^
Error: This expression has type pyobject Defunc.t
       but an expression was expected of type (unit -> pyobject) Defunc.t
       Hint: Did you forget to wrap the expression using `fun () ->'?
```

The problem is that the signature of `Pymodule.set` was changed as follows:
```ocaml
Py_module.t -> ?docstring:string -> string -> pyobject Defunc.t -> unit (* old *)
Py_module.t -> ?docstring:string -> string -> (unit -> pyobject) Defunc.t -> unit (* new *)
```

May I ask what motivated this change and how the following example should be updated:

```ocaml
open Base
open Python_lib
open Python_lib.Let_syntax

let add =
  let%map_open arg1 = positional "lhs" int ~docstring:""
  and arg2 = positional "rhs" int ~docstring:"" in
  python_of_int (arg1 + arg2)

let () =
  if not (Py.is_initialized ()) then Py.initialize ();
  let mod_ = Py_module.create "example_module" in
  Py_module.set mod_ "add" add (* error *)
```

**Comment by LaurentMazare** [comment]
Thanks for reporting this and sorry about the breakage, we just made some changes internally that hopefully will fix this for the next release.
The code should be simple to update, e.g. for the example you gave you just have to insert a `fun () ->`.
```ocaml
let add =
  let%map_open arg1 = positional "lhs" int ~docstring:""
  and arg2 = positional "rhs" int ~docstring:"" in
  fun () -> python_of_int (arg1 + arg2)
```

The rationale of the change is a bit tricky: when the python function is called, python_lib checks that all the arguments that get passed end up actually being used. With the old signature using a `pyobject Defunc.t`, this check will only take place *after* the function has been evaluated which can easily cause some confusion. With the new signature, the exhaustiveness check is performed when creating the `unit -> pyobject` closure so before evaluating it.
For what it's worth, the `Core.Command` module uses a similar trick and we should probably have included this in the first place.
